### ISSUE TITLE
请问无法打开游戏该如何解决

### ISSUE THREAD

**Issue by totpil** [bullhe4d/bigwaterlemon#1]
`Access to XMLHttpRequest at 'file:///D:/bigwaterlemon-main/res/import/07/079499991.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.`
`Failed to load resource: net::ERR_FAILED`
`Access to XMLHttpRequest at 'file:///D:/bigwaterlemon-main/res/import/07/07ce7530a.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.`
`cocos2d-js-min.js:6382 Error 4916, please go to https://github.com/cocos-creator/engine/blob/master/EngineErrorMap.md#4916 to see details. Arguments: 6dkeWRTOBGXICfYQ7JUBnG`

**请问进度条卡100%，chrome控制台报错，该如何解决**

**Comment by HarbinBear** [comment]
同问

**Comment by gj009351** [comment]
同问

**Comment by sunjiesama** [comment]
> `Access to XMLHttpRequest at 'file:///D:/bigwaterlemon-main/res/import/07/079499991.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.`
> `Failed to load resource: net::ERR_FAILED`
> `Access to XMLHttpRequest at 'file:///D:/bigwaterlemon-main/res/import/07/07ce7530a.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.`
> `cocos2d-js-min.js:6382 Error 4916, please go to https://github.com/cocos-creator/engine/blob/master/EngineErrorMap.md#4916 to see details. Arguments: 6dkeWRTOBGXICfYQ7JUBnG`
> 
> **请问进度条卡100％，chrome控制台报错，该如何解决**

服务协议打开，不能用文件协议打开

**Comment by sunjiesama** [comment]
> `Access to XMLHttpRequest at 'file:///D:/bigwaterlemon-main/res/import/07/079499991.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.`
> `Failed to load resource: net::ERR_FAILED`
> `Access to XMLHttpRequest at 'file:///D:/bigwaterlemon-main/res/import/07/07ce7530a.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.`
> `cocos2d-js-min.js:6382 Error 4916, please go to https://github.com/cocos-creator/engine/blob/master/EngineErrorMap.md#4916 to see details. Arguments: 6dkeWRTOBGXICfYQ7JUBnG`
> 
> **请问进度条卡100％，chrome控制台报错，该如何解决**
json跨域了，live server 端口协议打开就可以了，

**Comment by bxz123** [comment]
用手机怎么打开？

**Comment by bullhe4d** [comment]
> 用手机怎么打开？

手机的话需要上传到web服务器上。可以用公有云的对象存储。

**Comment by bxz123** [comment]
上传到服务器上了，但是他还是因为跨域卡100%，这样怎么解决啊

**Comment by bullhe4d** [comment]
> 上传到服务器上了，但是他还是因为跨域卡100%，这样怎么解决啊

project.js 1407行 url换成自己的域名，注释去掉。
