### ISSUE TITLE
加载到99卡住是什么原因？

### ISSUE THREAD

**Issue by TcTOrz** [bullhe4d/bigwaterlemon#14]

**Comment by zcx1218029121** [comment]
跨域了' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, weapp, https.

**Comment by zcx1218029121** [comment]
部署个web服务器即可

**Comment by zcx1218029121** [comment]
因为直接打开是file协议所以跨域了，用nginx代理就好了。

**Comment by TcTOrz** [comment]
好的，谢谢各位！
