### ISSUE TITLE
感谢  已成功部署

### ISSUE THREAD

**Issue by Joenothing-lst** [bullhe4d/bigwaterlemon#2]
作者您好!
我已成功部署，能否提供一下改动的地方，让我们参考学习一下?
如果有您写的备注就更好了.
谢谢!

**Comment by bullhe4d** [comment]
> 作者您好!
> 我已成功部署，能否提供一下改动的地方，让我们参考学习一下?
> 如果有您写的备注就更好了.
> 谢谢!

主要是在 project.js 1857行MainGameUi 方法下
` 
          t.prototype.adsButtonFunc = function() {` 
      `      console.log(b.default.Instance.targetFruit.destroy()) //销毁屏幕上方的水果` 
         `   b.default.Instance.createOneFruit(Math.floor(Math.random()*6)) //重新随机生成一个水果  ` 

游戏中水果生成的逻辑是在 1477行InputController 下， onTouchStart,onTouchMove,onTouchEnd这三个方法完成了游戏的基本逻辑

**Comment by Joenothing-lst** [comment]
十分感谢！
