### ISSUE TITLE
经常加载不出来或者卡进度

### ISSUE THREAD

**Issue by 1pone** [bullhe4d/bigwaterlemon#21]
好像经常会加载不出来或者卡进度，是网络环境的问题么或者是依赖国外源的文件？

**Comment by Kienyew** [comment]
似乎要服务器上运行。还有进度条是假的。
开个本机的服务器试试: `python -m http.server`

**Comment by qeqeq1** [comment]
请在web服务器上通过http（s）请求，在本地上点开协议是file 会导致被浏览器安全设置拦截

**Comment by jiawei-i** [comment]
跨域了，允许本地文件然后去project.js里面的1460左右那里把this.req.send(o)换成（其实就是this.req本地获取不到XMLHttpRequest,然后去下面那里把他404后的代码拿上来了。）
var t = a.launchScene,
                    n = a.Bros;
                    a.caS;
                    cc.director.loadScene(t, null, function () {
                       if (n) {"";
                          var e = document.getElementById("GameDiv");
                          e && (e.style.backgroundImage = "")
                       }
                       cc.loader.onProgress = null, console.log("Success to load scene: " + t)
                    })
