### ISSUE TITLE
接触到线后无法触发后续结算事件

### ISSUE THREAD

**Issue by ZhentangHe** [bullhe4d/bigwaterlemon#5]
首先非常感谢您能供提供代码.

我只是稍微修改了贴图和音效布署到pages上,但是在接触到线后却不能触发水果炸开以及分数结算.同时我注意到project.js 3374行一直在报错Unaught TypeError: Cannot read property 'position' of null. 但是我本人不是很了解js,请问您可以提供一些解决方法吗?

**Comment by Xpig4432xyx** [comment]
同问 我也遇到这个问题 死了以后就卡死

**Comment by woshizx** [comment]
楼主可否出个教程，让我们这些菜鸡稍微看懂点源代码

**Comment by bullhe4d** [comment]
游戏结束的问题已经修复了

**Comment by ZhentangHe** [comment]
> 游戏结束的问题已经修复了

非常感谢，测试了一下，水果确实可以炸开并进行加分了。

另外，游戏结算点击查看分数时界面直接关闭了，并没有打开分数结算界面（好像还有重开按钮？），gameEnd1应该是触发了，但是接下来报错project.js:1820 Uncaught ReferenceError: adBreak is not defined，我不太清楚这个adBreak是什么，看上去是个传参的函数。于是，我把所有adbreak删除了以后已经完全可以重开了：）
