### ISSUE TITLE
请问如何去掉右上角的广告呢？

### ISSUE THREAD

**Issue by tsotfsk** [bullhe4d/bigwaterlemon#7]

**Comment by wyfang** [comment]
同问

**Comment by jiawei-i** [comment]
去res/02/02de6eebb.json里面把按钮给去掉。
 "adsbutton": [
            {
              "__uuid__": "8bEQhVsqdIHb1u9XKoOwL+"
            },
            {
              "__uuid__": "40UZ49JRRHWYJHJtZTV6vr"
            }
          ],
          "adsbutton2": [
            {
              "__uuid__": "06IXvbwpRGbJot5Mk4S+BL"
            },
            {
              "__uuid__": "6ctrLi9rxJfatFF+AWULn7"
            }
          ],

**Comment by wyfang** [comment]
> 去res/02/02de6eebb.json里面把按钮给去掉。
> "adsbutton": [
> {
> "**uuid**": "8bEQhVsqdIHb1u9XKoOwL+"
> },
> {
> "**uuid**": "40UZ49JRRHWYJHJtZTV6vr"
> }
> ],
> "adsbutton2": [
> {
> "**uuid**": "06IXvbwpRGbJot5Mk4S+BL"
> },
> {
> "**uuid**": "6ctrLi9rxJfatFF+AWULn7"
> }
> ],

cool，不过我按照其他教程，直接改了图片和url，也不错。
