### ISSUE TITLE
添加代码注释

### ISSUE THREAD

**Issue by constown** [bullhe4d/bigwaterlemon#8]
我太菜了，看不懂源码……
希望可以添加一些代码注释，帮助阅读和理解源码。谢谢。

**Comment by p0page** [comment]
看起来作者应该是基于cocos2d魔改的吧？而不是直接动生成出来的代码

**Comment by Morris-Lucifer** [comment]
> 看起来作者应该是基于cocos2d魔改的吧？而不是直接动生成出来的代码

请问cocos2d是怎么导入项目的呢？小白弄了半天，官方教程的快速上手都没导入成功（菜哭）

**Comment by puzzle9** [comment]
这个应该是直接扣人家现成的

这个注释吧 还是从文档入手吧

**Comment by lzlu** [comment]
这是扒的JS压缩后的代码。原作者估计没开源。真要学把cocos2djs学一波，大差不差能写一个。
